model:
  type: "RandomForestClassifier"
  params:
    n_estimators : 100
    max_depth: 5
    random_state: 42


data:
  test_size: 0.2
  random_state: 42

output:
model_path: "app/models/artifacts/model.joblib"
metrics_path: "/app/models/artifacts/metrics.json"
