

services: 

  # Service 1: Training job
  train:
    build: .                      # build from dockerfile in current dir
    command: python src/train.py  #Override CMD from Dockerfile
    volumes:
      - ./models:/app/models      # Persist trained models
      - ./data:/app/data          # Share data with container
    environment:
      - PYTHONUNBUFFERED=1        # See print() outpu in real time

  # Service 2: Run tests
  test:
    build: .
    command: pytest tests/ -v
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src

  # Serivice 3: Interactive dev shell
  dev:
    build: .
    command: bash
    stdin_open: true
    tty: true
    volumes: 
      - .:/app                    # Mount entire project (live code changes)
    
